gifs = ['https://media.tenor.com/-7xFCtnyUCcAAAAM/uwu-ts-team-uwu.gif',
	  'https://c.tenor.com/8qTl-eokkR4AAAAC/uwu-smug.gif',
	  'https://c.tenor.com/tNIXtOf62wQAAAAd/tenor.gif',
	  'https://media.tenor.com/bn4xnRtfzosAAAAC/muy-bien.gif',
	  'https://media.tenor.com/AR8p1LHTOFEAAAAC/discord-uwu-sweat.gif',
	  'https://c.tenor.com/7FmzekCozzYAAAAM/uwu-cat.gif',
	  'https://c.tenor.com/CfmWkEvWvSUAAAAj/dance-uwu.gif',
	  'https://c.tenor.com/RLp8XZj8QzwAAAAj/uwu.gif',
	  'https://i.pinimg.com/originals/b7/5f/2c/b75f2c027971a82e62447a836466aa34.gif',
	  ]